"""create core tables

Revision ID: eebeff67e20d
Revises: 
Create Date: 2026-04-09 12:01:13.545529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eebeff67e20d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('puzzle_number', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_puzzle_number'), 'uploads', ['puzzle_number'], unique=False)
    op.create_table('extraction_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('upload_id', sa.String(), nullable=False),
    sa.Column('candidate_sequence', sa.Integer(), nullable=True),
    sa.Column('candidate_file_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('raw_result_json', sa.Text(), nullable=True),
    sa.Column('normalized_draft_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_jobs_status'), 'extraction_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_extraction_jobs_upload_id'), 'extraction_jobs', ['upload_id'], unique=False)
    op.create_table('review_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('extraction_job_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('markdown_path', sa.String(), nullable=False),
    sa.Column('candidate_file_path', sa.String(), nullable=True),
    sa.Column('issues_json', sa.Text(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['extraction_job_id'], ['extraction_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_records_extraction_job_id'), 'review_records', ['extraction_job_id'], unique=False)
    op.create_index(op.f('ix_review_records_status'), 'review_records', ['status'], unique=False)
    op.create_table('saved_puzzles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('puzzle_number', sa.Integer(), nullable=False),
    sa.Column('extraction_job_id', sa.String(), nullable=False),
    sa.Column('review_record_id', sa.String(), nullable=False),
    sa.Column('patches_file_path', sa.String(), nullable=False),
    sa.Column('patches_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['extraction_job_id'], ['extraction_jobs.id'], ),
    sa.ForeignKeyConstraint(['review_record_id'], ['review_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_puzzles_extraction_job_id'), 'saved_puzzles', ['extraction_job_id'], unique=False)
    op.create_index(op.f('ix_saved_puzzles_puzzle_number'), 'saved_puzzles', ['puzzle_number'], unique=False)
    op.create_index(op.f('ix_saved_puzzles_review_record_id'), 'saved_puzzles', ['review_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_puzzles_review_record_id'), table_name='saved_puzzles')
    op.drop_index(op.f('ix_saved_puzzles_puzzle_number'), table_name='saved_puzzles')
    op.drop_index(op.f('ix_saved_puzzles_extraction_job_id'), table_name='saved_puzzles')
    op.drop_table('saved_puzzles')
    op.drop_index(op.f('ix_review_records_status'), table_name='review_records')
    op.drop_index(op.f('ix_review_records_extraction_job_id'), table_name='review_records')
    op.drop_table('review_records')
    op.drop_index(op.f('ix_extraction_jobs_upload_id'), table_name='extraction_jobs')
    op.drop_index(op.f('ix_extraction_jobs_status'), table_name='extraction_jobs')
    op.drop_table('extraction_jobs')
    op.drop_index(op.f('ix_uploads_puzzle_number'), table_name='uploads')
    op.drop_table('uploads')
    # ### end Alembic commands ###
